| Metric Name                                                                                   | Type         | Description                                                | PromQL Query                                                                                                | Grafana Panel Idea                                                |
| --------------------------------------------------------------------------------------------- | ------------ | ---------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| `custom_app_requests_total`                                                                   | Counter      | Total HTTP requests received by the app                    | `custom_app_requests_total`                                                                                 | **Single stat / Counter**: Shows total requests so far            |
| `orders_created_total`                                                                        | Counter      | Total number of orders created                             | `orders_created_total`                                                                                      | **Time series**: Shows how orders increase over time              |
| `payments_success_total`                                                                      | Counter      | Total successful payments                                  | `payments_success_total`                                                                                    | **Time series or Gauge**: Compare with failed payments            |
| `payments_failed_total`                                                                       | Counter      | Total failed payments                                      | `payments_failed_total`                                                                                     | **Time series or Gauge**: Useful for error alerting               |
| `active_sessions`                                                                             | Gauge        | Number of active users currently online                    | `active_sessions`                                                                                           | **Gauge panel**: Real-time users online                           |
| `http_request_duration_seconds_count`                                                         | Histogram    | Total count of HTTP requests recorded in latency histogram | `http_request_duration_seconds_count`                                                                       | **Graph / Heatmap**: Total requests over time by endpoint         |
| `http_request_duration_seconds_sum`                                                           | Histogram    | Sum of request durations (for avg latency calculation)     | `http_request_duration_seconds_sum`                                                                         | **Graph / Stat**: Compute average latency                         |
| `http_request_duration_seconds_bucket`                                                        | Histogram    | Buckets of request durations                               | `rate(http_request_duration_seconds_bucket[1m])`                                                            | **Heatmap / Histogram panel**: Shows request latency distribution |
| `orders_created_total / custom_app_requests_total`                                            | Derived      | Ratio of orders per request                                | `rate(orders_created_total[5m]) / rate(custom_app_requests_total[5m])`                                      | **Graph panel**: Order conversion rate                            |
| `payments_success_total / (payments_success_total + payments_failed_total)`                   | Derived      | Payment success rate                                       | `(rate(payments_success_total[5m])) / (rate(payments_success_total[5m]) + rate(payments_failed_total[5m]))` | **Graph / Stat panel**: Payment success percentage                |
| `rate(custom_app_requests_total[1m])`                                                         | Counter rate | Requests per minute                                        | `rate(custom_app_requests_total[1m])`                                                                       | **Graph panel**: Request throughput                               |
| `rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])` | Derived      | Average request latency in seconds                         | `rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])`               | **Graph panel**: Shows average latency trend                      |
